import {
  SUCCESS_BACKGROUND_COLOR,
  SUCCESS_TEXT_COLOR,
  ERROR_BACKGROUND_COLOR,
  ERROR_TEXT_COLOR,
  INFO_BACKGROUND_COLOR,
  INFO_TEXT_COLOR,
  WARNING_BACKGROUND_COLOR,
  WARNING_TEXT_COLOR,
  DEFAULT_TEXT_COLOR,
} from './colors';

export {
  SUCCESS_BACKGROUND_COLOR,
  SUCCESS_TEXT_COLOR,
  ERROR_BACKGROUND_COLOR,
  ERROR_TEXT_COLOR,
  INFO_BACKGROUND_COLOR,
  INFO_TEXT_COLOR,
  WARNING_BACKGROUND_COLOR,
  WARNING_TEXT_COLOR,
  DEFAULT_TEXT_COLOR,
};
