name: GitHub_Actions

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  eslint_checking:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
      - name: Git clone my repo
        uses: actions/checkout@v2

      - name: Run code eslint lint
        uses: stefanoeb/eslint-action@1.0.2
        with:
          files: src/
        env:
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  publish_project_to_github_packages:
    name: Github packages
    runs-on: ubuntu-latest
    needs: [eslint_checking]
    steps:
      - name: Git clone my repo
        uses: actions/checkout@v2
      - name: Publish
        run: npm publish
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
  finish-actions:
    name: Message of completing GitHub Actions
    runs-on: ubuntu-latest
    needs: [eslint_checking, publish_project_to_github_packages]
    steps:
      - run: echo "Everything is good! All steps is completed successfully."
