name: Node continuous integration

  on:
    pull_request:
      branches: [master]

  jobs:
    pull_request:
      name: Lint code base
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Run code base lint
          uses: github/super-linter@v3
          env:
            DEFAULT_BRANCH: master

