name: Node continuous integration

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  pull_request:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run code eslint lint
        uses: stefanoeb/eslint-action@1.0.2
        with:
          files: src/
        env:
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
