name: GitHub_Actions

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  eslint_checking:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run code eslint lint
        uses: stefanoeb/eslint-action@1.0.2
        with:
          files: src/
        env:
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  finish-actions:
    name: Message of completing GitHub Actions
    needs: [eslint_checking]
    run: echo "Everything is good! All steps is completed successfully."
